import streamlit as st
import pandas as pd
import joblib

# Load the trained model, scaler, and feature ranges
model = joblib.load("aircraft_maintenance_model.pkl")
scaler = joblib.load("scaler.pkl")
feature_ranges = joblib.load("feature_ranges.pkl")

# General information
st.set_page_config(page_title="Aircraft Maintenance Prediction", layout="centered")
st.title("Aircraft Maintenance Prediction App")
st.markdown(
    """
    ### Welcome to the Aircraft Maintenance Prediction Tool!
    This app uses a machine learning model to predict the **maintenance rating** of an aircraft based on various input features.

    **Note:**
    - All inputs are scaled between **0-100** for simplicity.
    - **Higher values are better** for features like "Structural Integrity Score" and "Engine Type."
    """
)

# Styling for improved UI
st.markdown(
    """
    <style>
    .feature-box {
        padding: 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
        margin-bottom: 15px;
        background-color: black;
    }
    .feature-title {
        font-size: 16px;
        font-weight: bold;
        margin-bottom: 5px;
        color: red;
    }
    .divider {
        margin: 15px 0;
        border-top: 1px solid #ccc;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# Input collection
st.markdown("### Input Aircraft Data")
input_data = {}
for feature, (min_val, max_val) in feature_ranges.items():
    unit_change = (max_val - min_val) / 100  # Scale adjustment
    input_scaled_value = st.slider(
        f"{feature} (Scaled Range: 0 to 100)",
        0,
        100,
        50,
        help=f"Original range: [{min_val:.2f}, {max_val:.2f}]",
    )
    # Convert scaled value back to the original range
    original_value = min_val + (input_scaled_value / 100) * (max_val - min_val)
    st.markdown(
        f"""
        <div class="feature-box">
            <div class="feature-title">{feature}</div>
            <div>Entered Scaled Value: {input_scaled_value}</div>
            <div>Corresponding Original Value: {original_value:.2f}</div>
        </div>
        <div class="divider"></div>
        """,
        unsafe_allow_html=True,
    )
    input_data[feature] = original_value  # Save the original value

# Convert input data to DataFrame
input_df = pd.DataFrame([input_data])

# Scale input data to match model's training scale
scaled_input = scaler.transform(input_df)

# Predict aircraft rating
scaled_prediction = model.predict(scaled_input)[0]
aircraft_rating = scaled_prediction

# Determine rating category
if aircraft_rating < 40:
    rating_level = "Poor"
elif 40 <= aircraft_rating < 60:
    rating_level = "Fair"
elif 60 <= aircraft_rating < 80:
    rating_level = "Good"
else:
    rating_level = "Excellent"

# Display results
st.markdown("### Prediction Results")
st.success(f"The predicted aircraft maintenance rating is: **{aircraft_rating:.2f}**")
st.info(f"The predicted rating level is: **{rating_level}**")

# Add a footer
st.markdown(
    """
    ---
    **Developed by:** Shuvam Singh  
    **Disclaimer:** The results are generated by a machine learning model and are for reference purposes only.
    """
)